In [47]:
my_list = [1,2,3]
import numpy as np

arr = np.array(my_list)
print(arr)

[1 2 3]


In [48]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_mat2=[[-1,2,3],[-4,5,6],[-7,8,9]]




In [49]:
print(my_mat)
print(np.array(my_mat)-np.array(my_mat2))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[ 2  0  0]
 [ 8  0  0]
 [14  0  0]]


In [50]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [51]:
np.zeros(3)

array([0., 0., 0.])

In [52]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
np.ones(4)

array([1., 1., 1., 1.])

In [54]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [56]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.random.rand(5)

array([0.42811802, 0.33206507, 0.84246701, 0.03096565, 0.76696933])

In [58]:
np.random.rand(5,5)

array([[0.61954383, 0.1916913 , 0.39678536, 0.4225957 , 0.69792739],
       [0.49155252, 0.27790294, 0.56117387, 0.15514246, 0.45786981],
       [0.15675647, 0.09910325, 0.14592309, 0.22199975, 0.88709297],
       [0.23746814, 0.44269363, 0.13052745, 0.37310797, 0.14334085],
       [0.54936161, 0.39032826, 0.26151288, 0.33114734, 0.85719195]])

In [59]:
np.random.randn(4,4)

array([[ 0.26395264,  0.5581811 , -1.13273125,  0.26318709],
       [ 0.43875068,  0.63230476,  0.60290499,  0.20299626],
       [-2.40744805, -1.29046584, -2.34891738,  0.23988498],
       [-1.6112933 ,  2.23926373,  0.43499539,  0.10845845]])

In [60]:
np.random.randint(1,100,(4,4))

array([[59, 68, 96, 22],
       [ 5, 51, 69, 20],
       [66, 27, 44, 97],
       [96, 76, 49, 76]])

In [61]:
arr = np.arange(25)
ranarr=np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[37 12 43 12 33 28 17 43 11 30]


In [62]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
ranarr.max()

43

In [64]:
ranarr.min()

11

In [65]:
ranarr.argmax()

2

In [66]:
ranarr.argmin()

8

In [67]:
arr.shape

(25,)

In [68]:
arr.dtype

dtype('int64')