In [ ]:
import numpy as np

In [44]:
arr= np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

In [ ]:
arr[1:7]

In [ ]:
arr[0:5]

In [ ]:
arr[:6]

In [ ]:
arr[3:]

In [ ]:
arr[-1:] #last one

In [ ]:
arr[0:5]=100

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:]=100

In [ ]:
arr_copy

In [ ]:
arr

In [20]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [26]:
arr_2d[1][2]
arr_2d[1,2]

30

In [22]:
arr_2d[2]

array([35, 40, 45])

In [28]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
bool_arr=arr > 5

In [32]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [33]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [34]:
arr[arr<3]

array([0, 1, 2])

In [35]:
arr_2d=np.arange(50).reshape(5,10)

In [43]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])